import './carrito/closeCarrito';
import './tabs/tabs';
import './cargarProductos/cargarProducto';
import './cargarProductos/eventDatos';
import './carrito/agregarCarrito';
import './cargarProductos/cargarSmallGallery';
import './carrito/boleta';
import './carrito/deleteProd';
import './carrito/itemCarritoNav';